### ISSUE TITLE
Bug: release-v3.3 docker-compose.yml  config.error

### ISSUE THREAD

**Issue by dingchunqiuzyz** [openimsdk/open-im-server#1352]
### What happened?

the mongo config tag is not close 
see:
- ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro"

### What did you expect to happen?

fix it.

### How can we reproduce it (as minimally and precisely as possible)?

remove the """

### Anything else we need to know?

why i remove the ", mongo image can not start? 
 mongo:6.0.2                           "docker-entrypoint.s…"   44 seconds ago   Restarting (132) 5 seconds ago    

why always Restarting ?

### version

<details>
```console
$ {name} version
see:
- ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro"
```
</details>

### Cloud provider

<details>
see:
- ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro"
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
Thank you for reporting this and for the follow-up with your findings. It's great to hear that you were able to identify the cause of the issue.

Regarding the resolution, you're correct that the erroneous " at the end of line 39 in the docker-compose.yaml file would cause issues when starting the service. This should be fixed by simply removing the stray quotation mark.

As for your question about the MongoDB container not starting after removing the quote, this might be related to a different configuration issue. The container's restart behavior seems to indicate that it's trying to recover from a failure. The exit code (132) can sometimes relate to illegal instructions, which could be a sign of incompatibility between the MongoDB image and your Linux system's architecture or a misconfiguration.

To help you further, could you please provide:

The complete docker-compose configuration (if possible, please ensure there are no sensitive data in it).
The logs from the MongoDB container which can be retrieved using docker logs [container_id] command. This might provide more insight into why the MongoDB service isn't starting properly.
