### ISSUE TITLE
Roadmap-v3.5:  Reduce storage components, optimize operations and deployment.

### ISSUE THREAD

**Issue by skiffer-git** [openimsdk/open-im-server#1400]
#### Objective

Develop a production-grade IM system to fully capture user engagement and loyalty.

#### Complete Testing Plan and Report

Message reliability and performance testing plan, including test scripts. Assigned to Gordon.

#### Technical Architecture

- Replace MySQL with MongoDB. Assigned to Chao and Xinwei.
- Optimize heartbeat process. Assigned to Gordon.

#### Deployment

Improve the version upgrade process for a smoother update experience. Assigned to Xinwei.

#### Operations

- Fault tolerance at the code level. Assigned to Tim.
- Monitoring and alerting in Kubernetes. Assigned to Tim.
- Log collection in Kubernetes. Assigned to Tim.

#### Features

- Implement webhook functionality. Assigned to Brabem and CCM.
- Provide a C++ version of the SDK. Assigned to CCM.

**Comment by lucasjinreal** [comment]
Any timeline on v3.5? Really hope all migrate to mongoldb, do not using mysql any longer.

**Comment by Bmixo** [comment]
Is that possible to provide a substitute option for replacing all Java components? Because if one company writes all its products in Go, the best option for them is their developer can understand all the components behind their system, and if facing some problems they are required to know how to modify the source code and handle the problem. This IM product already includes MySQL MongoDB(which is written in C++), and OpenIm component written in Go, and Kafka written in Java, and desktop and mobile written in vue (javascript, typescript html css )and flutter (dart) and Android SDK write in java and ios sdk write in object-c, and it require to hire many developers with experience in different languages  for future develop）

**Comment by cubxxw** [comment]
The issue has been resolved.

---
這個問題已經解決

**Comment by caesar168** [comment]
niubility！！！
