### ISSUE TITLE
Bug: deploy openim server in docker mode, can't pull all docker images

### ISSUE THREAD

**Issue by yhuaqiang** [openimsdk/open-im-server#1418]
### What happened?

the last step docker compose up -d
can't pull images, will abort in several seconds

### What did you expect to happen?

the last step docker compose up -d
can't pull images, will abort in several seconds

### How can we reproduce it (as minimally and precisely as possible)?

the last step docker compose up -d
can't pull images, will abort in several seconds

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by yhuaqiang** [comment]
<img width="930" alt="6290b45c87cb4c89b35afb5b8e1bb43" src="https://github.com/openimsdk/open-im-server/assets/5283803/d0d6260f-1adc-447e-b357-623cb7cf875b">

**Comment by yhuaqiang** [comment]
if pull one image at a time, it will be ok

**Comment by cubxxw** [comment]
It looks like you're having an issue with Docker where you're unable to pull all the necessary images for deploying an OpenIM server. The error message indicates that the connection is being refused when trying to pull the images, which often happens due to network issues, firewall configurations, or issues with the Docker daemon itself.

Here are a few steps you might consider to troubleshoot and resolve this issue:

1. **Check Network Connection**: Ensure that your server has a stable internet connection and can reach the Docker Hub or other image registries.
2. **Firewall and Security Groups**: Check if there are any firewall rules or security groups that may be blocking the outgoing connections on port 443, which is used for HTTPS connections.
3. **Docker Service**: Make sure the Docker service is running properly on your system. You can restart the service using `systemctl restart docker` on a systemd-based system.
4. **Pull Images Individually**: As you mentioned, pulling images one at a time might help. You can do this by using `docker pull [image-name]` for each image before running `docker-compose up -d`.
5. **Docker Compose Version**: Ensure that you are using a compatible version of Docker Compose for your Docker engine and the `docker-compose.yml` file you are using.
6. **Resource Limits**: Check if there are any resource limits set on your Docker or system that might be causing the process to abort.
7. **Proxy Settings**: If you are behind a proxy, you may need to configure Docker to use your proxy settings.
8. **Docker Hub Limits**: Be aware that Docker Hub imposes rate limits on image pulls. If you've exceeded these limits, you might face issues pulling images.
9. **DNS Resolution**: Ensure that your DNS settings are correct and that your server can resolve the domain names of the image repositories.
10. **Docker Logs**: Check the Docker daemon logs for more detailed error messages that could provide additional insight. You can typically find these logs using `journalctl -u docker.service`.

**Comment by yhuaqiang** [comment]
my docker version is  24.0.7. 
after pull images Individually, when run docker-compose up -d,
it report an error again.
![image](https://github.com/openimsdk/open-im-server/assets/5283803/c3b10648-1b4c-4e5e-b713-66a5a7058e2d)

**Comment by cubxxw** [comment]
I am confident that I can find a solution to the error mentioned below on Google. I am willing to search for the problem and resolve it. Please feel free to leave a comment.

**Comment by yhuaqiang** [comment]
the reason is fastgithub proxy .
