### ISSUE TITLE
Bug: update user's info will reset user's registered time.

### ISSUE THREAD

**Issue by FGadvancer** [openimsdk/open-im-server#1445]
### What happened?

User's registered time modified when i call /user/update_user_info this router.

### What did you expect to happen?

Just change user's nickname or avatar,do not change account create time.

### How can we reproduce it (as minimally and precisely as possible)?

Invoke /user/update_user_info this restful api,user's create time will be reset.

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

<details open>
<summary>Checklist</summary>

- [X] Modify `internal/rpc/user/user.go` ! No changes made

![Flowchart](https://raw.githubusercontent.com/openimsdk/open-im-server/sweep/assets/22deeee4712568fc942c828a18cfc607a0428e1e43d7c5a1f7fece8382cac76d_1445_flowchart.svg)
</details>

**Comment by cubxxw** [comment]
I can help you with that. Based on the issue description, it seems that when calling the `/user/update_user_info` API in the OpenIM system, the user's registered time is being reset. The user expects that only the user's nickname or avatar should be changed, without affecting the account creation time.

1. Identify the code responsible for updating the user's information in the `/user/update_user_info` API.
2. Review the code logic to understand why the registered time is being modified.
3. Check if there are any unnecessary operations or incorrect data handling that could be causing the issue.
4. Modify the code logic to ensure that updating the user's nickname or avatar does not reset the account creation time.
5. Test the modified code thoroughly to verify that the issue is resolved and that the registered time remains unchanged.
6. Once you have confirmed that the issue is fixed, provide the solution as a reply to the GitHub issue, explaining the steps taken to resolve it.
