### ISSUE TITLE
[BUG] After calling the group message history list interface, the openim-rpc-msg service hangs up.

### ISSUE THREAD

**Issue by leejunl** [openimsdk/open-im-server#2840]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

![1](https://github.com/user-attachments/assets/9671f842-bbfa-4390-8969-c0c0ff43e386)
![2](https://github.com/user-attachments/assets/52e8b70a-b446-400e-ac31-b4def5cc68f8)

**Comment by skiffer-git** [comment]
Give mage check a run to check it out.

**Comment by withchao** [comment]
A large number of errors in the log are caused by non-existent records. When calling SearchMessage, it crashed, and the specific reason was not shown in the log. Under normal circumstances, administrator calls will not cause errors such as non-existent records. Have you modified the database yourself?
